### ISSUE TITLE
Chat bubble transparency

### ISSUE THREAD

**Issue by doomkittenplays** [Haplo064/ChatBubbles#1]
Hey there! Absolutely love this plugin. Makes crowded city chatter much better.

I have a feature request. It'd be cool to add transparency settings to the background color of the bubble where it's just a slider ranging from completely transparent to black. I think that would solve the issue of not being able to see certain colors well.

**Comment by Wistelle** [comment]
Alternatively, being able to change the colour of the bubble would be another solution to the above problem, and allow additional customization.

**Comment by Haplo064** [comment]
Has been looked into, but it is not a simple fix.
Feature enhancement *may* come in the future, if I have a better idea on how to link two separate areas of code.

**Comment by decoytrix** [comment]
I love the idea of changing the bubble color as well.  I was hoping to make the text color match my chatlog color when it comes to message types, but that only really works if I can set the background of the bubble to be dark like the chatbox, at least if I want any visibility.

**Comment by Haplo064** [comment]
Colours added.
Awaiting dalamud update before pushing out.
