### ISSUE TITLE
Question for Haplo064

### ISSUE THREAD

**Issue by mfloob** [Haplo064/ChatBubbles#10]
Hi Haplo,

I appreciate the work here. Do you mind if I ask you some questions about reversing FF14. Through Discord or some other? All the plugin creators seem to have found custom signatures and I haven't quite been able to get what I'm looking for.

Thanks

**Comment by Haplo064** [comment]
Ping me on the discord, no problem.
Just go to the `goat place` server and I'm there.
I'm much more active there than on git.
