### ISSUE TITLE
Installed through XIV Launcher. Chat bubbles not appearing.

### ISSUE THREAD

**Issue by Calibrumm** [Haplo064/ChatBubbles#11]
title. I cross-checked my settings with my friend who has them working and disabled all other plugins but still nothing. the only difference between his install and mine is that I own FFXIV through Steam and he doesn't, but I cant imagine that's an issue as all other plugins work.

**Comment by gothonarampage** [comment]
I too am having this issue, and also have the steam version.

**Comment by Haplo064** [comment]
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.
