### ISSUE TITLE
Specific Emote Bubble Location

### ISSUE THREAD

**Issue by SonyUSA** [Haplo064/ChatBubbles#12]
There is one specific emote (sorry I just started I don't know which) that displays text that places the bubble over your own head. Likely because the %t is not the first word. The text is something like:

"The sight of X springs a question to Y..."

May need a special parser exception for that emote to pull the target from the 4th word... :)

**Comment by Haplo064** [comment]
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.
