### ISSUE TITLE
[Feature Request] Chat bubble background

### ISSUE THREAD

**Issue by livvydoodlez** [Haplo064/ChatBubbles#17]
I love the chat bubble, but would it be possible to change the background color of the bubble itself, as well as the color of the text? It wouldn't be as hard to read.

**Comment by Iaotle** [comment]
+1

**Comment by InTheBeef** [comment]
+1

**Comment by Haplo064** [comment]
It's you lucky day.
Added in new build, and awaiting a dalamud update before pushing it out.

**Comment by Iaotle** [comment]
woo!
