### ISSUE TITLE
Highlighting certain words inside the chat bubbles?

### ISSUE THREAD

**Issue by mondomx** [Haplo064/ChatBubbles#2]
Hi, I'm loving your plug-in and I use it a lot. I wanted to ask, is there a way we could get a box to introduce important words (maybe separated by spaces) that we want to pay special attention to and then having those words highlighted in a selected color in the chat bubble?

It would be awesome so we could (for example) put our name or a word in said textbox and have it colored whenever someone uses it in a message, to draw our attention to the chat bubble of the people we're conversing with.

Thanks! :)

**Comment by Haplo064** [comment]
Coming in a side release in the future, as part of chat enhancements. (No ETA, I'll leave this open until that project is made)

**Comment by Haplo064** [comment]
Can be acheived through other plugin cross-functions, as any changes to text will be replicated in chat bubbles.
