### ISSUE TITLE
Chat Bubbles for emotes appear over the target player instead of self

### ISSUE THREAD

**Issue by flames5123** [Haplo064/ChatBubbles#20]
This is for any emote, but not custom emotes. For example, "You laugh at {t}" will appear over {t}'s head, but when they do the emote, it also appears over their head.

This didn't happen before the QuickLauncher updated this past week (10/05).

If more info is needed, let me know.

Thanks!

**Comment by Haplo064** [comment]
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.
