### ISSUE TITLE
Custom emote bubbles missing character names

### ISSUE THREAD

**Issue by AnophelesAnax** [Haplo064/ChatBubbles#21]
not sure if this is possible to implement, but currently using the custom emotes channel (/em) puts the message in the chat bubble but without your character name for example:

typing "/em pats the chocobo"
produces "<character name> pats the chocobo" in the emotes channel
but only puts "pats the chocobo" in the dialogue bubble.

if you could automatically append your character name to the front of custom emote bubbles (as it's displayed in the emote chat) then that would fix things.

**Comment by Haplo064** [comment]
Fixed in new build.
Awaiting dalamud update before pushing.
