### ISSUE TITLE
Option to base chat bubble timer on chat message length

### ISSUE THREAD

**Issue by vinajuliette** [Haplo064/ChatBubbles#24]
Longer lines take longer to read, so closing the chat bubble should be, optionally at least, based on the length of the sentence times a factor.

For example, if enabled the timer could show for 4 seconds for every 10 characters displayed. If someone says "hi" it will show for 4 seconds, but if they write a small book it will last longer.

This would also necessitate a floor and ceiling number e.g 4 seconds minimum and 30 seconds maximum so if someone spams a lot of text it would still be removed relatively quickly

**Comment by Haplo064** [comment]
Added in new build.
Awaiting dalamud update before pushing it out.
