### ISSUE TITLE
[Bug] Chat bubble appears over the wrong player

### ISSUE THREAD

**Issue by fournm** [Haplo064/ChatBubbles#26]
If you type a message with a `<t>` pointing at another player, the bubble appears over that other player's head. It doesn't matter if the target variable is at the front or somewhere in the middle of the message.

**Comment by Haplo064** [comment]
Cannot reproduce, believed to be fixed in new build.
Awaiting dalamud update before pushing out.

**Comment by TwistedAkai** [comment]
I'm getting this when using <2> and so on. v1.3.2.2
