### ISSUE TITLE
Bubbles sometimes stuck in the screen.

### ISSUE THREAD

**Issue by Huijiro** [Haplo064/ChatBubbles#28]
I don't know the cause of it, but sometimes bubbles can simply become stuck in screen-space. My theories are either a problem when too many bubbles are generated since it seems to happen more occasionally with full places with a lot of talk.

I would like to ask for a command if possible to reset all bubbles from screen, delete all of them.

**Comment by Haplo064** [comment]
I've added a soft reset of bubbles via the command:
`/bub clear`
