### ISSUE TITLE
[Request] Typing bubble above head.

### ISSUE THREAD

**Issue by KotoriTakamiya** [Haplo064/ChatBubbles#30]
Hey! I love this plugin! it surely brings this game to a whole new level!
and I was thinking if it could be possible to add a "Typing bubble" above their head once they start typing a message to us.
It is possible? Would be nice.

**Comment by BSoD38** [comment]
I don't think this is possible as FFXIV doesn't have anything to indicate that a player is typing a message.

**Comment by Haplo064** [comment]
Sadly impossible to implement without SE changing their chat engine entirely.
