### ISSUE TITLE
Bubbles don't follow character while fading out

### ISSUE THREAD

**Issue by KitF** [Haplo064/ChatBubbles#31]
If you move the camera while a bubble is fading out, it no longer follows the character and instead stay in the position they are in when the fadeout started.

**Comment by KitF** [comment]
I think this might be a bug with the game itself rather than this specific plugin.

**Comment by Haplo064** [comment]
This is indeed a flaw in the way the game implemented bubbles, which I am using for my plugin.
Unless I get a job at SE and fix it there, this will remain an issue.
