### ISSUE TITLE
Update to latest version of Dalamud

### ISSUE THREAD

**Issue by Tudi20** [Haplo064/ChatBubbles#32]

**Comment by Ravenette** [comment]
Yus, that'd be nice! This is by far the most useful plugin for me. <3

**Comment by pynom** [comment]
If you are in dire need of this plugin (who isn't) and you can no longer wait go to the windows searchbar and type this in %appdata%\XIVLauncher\installedPlugins open the folder then download this release https://github.com/pynom/ChatBubbles/releases/download/Release/ChatBubbles.zip and throw the folder from the extracted zip in there

**Comment by fSatoru** [comment]
Thank you @pynom! It worked nicely!

**Comment by ele-starshade** [comment]
Can also place the .dll into a folder, and then point "Dev Plugin Locations" to the dll; 
![image](https://user-images.githubusercontent.com/61023752/163693725-f15e55af-46ce-4a80-ba96-7d242d8db9cb.png)

Doesn't replace the original mod so when it gets updated you can just disable the dev one and enable the main-line one again :)

Just an alternative way of consuming Pynoms dll! Thanks Pynom, working brilliant. <3

**Comment by Iaotle** [comment]
@pynom I added your repo to my dalamud plugins list until the original gets an update

**Comment by xaannn** [comment]
@pynom can you try to port https://github.com/akira0245/MidiBard too? i think its discontinued tyvm

**Comment by pynom** [comment]
> @pynom can you try to port https://github.com/akira0245/MidiBard too? i think its discontinued tyvm

It didn't break it just got secure disabled by Dalamud you can just go to %appdata%\XIVLauncher\installedPlugins\MidiBard\1.9.3.0 open MidiBard.json with a text editor and make sure these settings are active

  "Disabled": false,
  "Testing": false,
  "DalamudApiLevel": 6,

**Comment by Haplo064** [comment]
Just an FYI that I'm away from my pc for a week, so the legit version won't be updated for at least that time.

When I get back it'll be updated to work with the latest version and have some fancy new features I've been cooking up.

**Comment by JaneSmith** [comment]
@pynom Will that fix also work for [GoodMemory](https://git.sr.ht/~jkcclemens/GoodMemory)? Thanks.

**Comment by lovelydumpling** [comment]
> @pynom Will that fix also work for [GoodMemory](https://git.sr.ht/~jkcclemens/GoodMemory)? Thanks.

That's irrelevant to this plugin but isn't Good Memory redundant now anyway? the game now has this feature built in

**Comment by lemabr01** [comment]
@lovelydumpling Good Memory would also include faded Orchestrion Rolls and some other things the built-in version does not.
