### ISSUE TITLE
[Request] Distance Filtering

### ISSUE THREAD

**Issue by UrthemieI** [Haplo064/ChatBubbles#34]
Would you be willing to add a feature that allows you to set chat bubbles to only be displayed if the speaker is within a set distance from the player?

**Comment by RaZz0r65** [comment]
I would like this too if possible

**Comment by Haplo064** [comment]
Will add for the next feature update.

**Comment by Haplo064** [comment]
![image](https://user-images.githubusercontent.com/11189337/166861904-f71699a9-01b4-47ef-b468-229c6686718a.png)
Added.
