### ISSUE TITLE
Wrong bubble position when sending a message with three characters

### ISSUE THREAD

**Issue by aradiel** [Haplo064/ChatBubbles#37]
Really odd bug showed up while I was testing colors for bubbles: If you send a message with the text "say" the bubble will appear in front of your face instead of on top of your character. I'm not sure what could be causing it. If you put anything before or after the word, it will show on top as expected.
![image](https://user-images.githubusercontent.com/22911153/166082716-6238c7ac-6c58-436c-8044-a6b063d8306d.png)
![image](https://user-images.githubusercontent.com/22911153/166082728-2b61ecce-529e-4549-a31f-55d414b03138.png)

**Comment by Sephirithane** [comment]
I've also had issues with the bubble positions being in the wrong place. They sometimes appear on the center of my character instead of above my head.

**Comment by Sc0rps91** [comment]
**Can i know how you changed the size of the bubble and the color please ? <3

thanks**

**Comment by aradiel** [comment]
Changed title to reflect more testing, bug seems to happen with any three character message like "lol" or "123".

@Sc0rps91 I haven't changed the size, but you can change both by entering the plugin options either in the dalamud window or by typing /bub in chat

**Comment by Sc0rps91** [comment]
> Titre modifié pour refléter plus de tests, un bogue semble se produire avec n'importe quel message à trois caractères comme "lol" ou "123".
> 
> @Sc0rps91Je n'ai pas changé la taille, mais vous pouvez changer les deux en entrant les options du plugin soit dans la fenêtre dalamud soit en tapant /bub dans le chat

thanks alot for the response but i dont have the size chat option ... 

here is the screen : 

![image](https://user-images.githubusercontent.com/104631060/166108637-d4f86af4-dcf7-4757-8a78-38d7d262c9c7.png)


can you please tell me exactly where is the size bubble chat option?

thanks alot

**Comment by 0kie** [comment]
It is not only three characters, it can happen with any text length 
![test](https://user-images.githubusercontent.com/82538043/166122260-3ab8980e-180b-4ff5-be1d-3a1369e688a1.png)

**Comment by ele-starshade** [comment]
The worst one was when dancing, it attaches to your hand and flies around all over the place. Hilarious but impossible to read xD Would be great if we could try and get a fix for this soon!

**Comment by Sc0rps91** [comment]
It is difficult to read the text because the size of the bubble is very small. Is there a way to enlarge the size of the bubble?

**Comment by aradiel** [comment]
this issue seems to have been resolved in the lastest version, I'm closing this. Sc0rps I don't think there's a way yet since scaling is not doing anything, hopefully that option will be what you need when it starts working
