### ISSUE TITLE
Messages sometimes double queue

### ISSUE THREAD

**Issue by Sevii77** [Haplo064/ChatBubbles#39]
Using the Queue option messages seem to double Queue

https://user-images.githubusercontent.com/20374966/166106383-7beb7cc2-8a03-4feb-b263-ee8409ea3788.mp4

**Comment by Haplo064** [comment]
I am aware of this but the fix currently eludes me.
Leaving this here until I resolve it.

**Comment by Haplo064** [comment]
Resolved as of https://github.com/Haplo064/ChatBubbles/commit/82cf5ae88ed9ebd94040b23b91da795593c15401
