### ISSUE TITLE
Text length scaling hiding messages sent after bubble timer passes

### ISSUE THREAD

**Issue by aradiel** [Haplo064/ChatBubbles#40]
If you send a longer message with the scaling enabled, and send another one after the set bubble timer has passed, the new message will not be queued, stacked nor replaced. Easily reproduced by setting bubble timer to 1 and sending a long message.

https://user-images.githubusercontent.com/22911153/166109098-94e10aec-f1c8-4de9-85e1-cfb57c007130.mp4

**Comment by Haplo064** [comment]
Thanks, I'll look into this and tweak the code to resolve it.

**Comment by Haplo064** [comment]
https://user-images.githubusercontent.com/11189337/166851869-c23227a9-64eb-414b-b9e4-6987bdb3c3ba.mp4

Resolved as of https://github.com/Haplo064/ChatBubbles/commit/7974a9b8aabe689662332a2a36e7af293f4034ee
