### ISSUE TITLE
Regression: bubbles are small on a 4k monitor

### ISSUE THREAD

**Issue by Maia-Everett** [Haplo064/ChatBubbles#42]
I don't know if this is due to pixel density or something else, but on my 3840x2160 monitor, chat bubbles have become very small after the update. They were correctly sized before 6.1.

![image](https://user-images.githubusercontent.com/10684/166133922-fd7129be-3f2a-47f7-a350-a10fbb7bbd38.png)

**Comment by Haplo064** [comment]
Bubble scale! It's now an option.
It overrides your default setting in the game to allow for custom sizes, seperate from the game's setting.

Open up the config and fiddle with it to get them to your liking (/bub).
