### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by ichi-obi** [Haplo064/ChatBubbles#52]

**Comment by WccKonig** [comment]
or you can grab the 3rd party fix from cecilia-sanare until this repo is fixed, as posted in their PR (#50).
https://raw.githubusercontent.com/cecilia-sanare/ChatBubbles/cecilia/repo.json

**Comment by Tudi20** [comment]
*to 7.0 now

**Comment by basedmatt** [comment]
> or you can grab the 3rd party fix from cecilia-sanare until this repo is fixed, as posted in their PR (#50). https://raw.githubusercontent.com/cecilia-sanare/ChatBubbles/cecilia/repo.json

Is this still working as of now?

**Comment by EnigmaMoon** [comment]
> > or you can grab the 3rd party fix from cecilia-sanare until this repo is fixed, as posted in their PR (#50). https://raw.githubusercontent.com/cecilia-sanare/ChatBubbles/cecilia/repo.json
> 
> Is this still working as of now?

I tried the URL today and can't seem to find it in XIVLauncher.

**Comment by cecilia-sanare** [comment]
> > > or you can grab the 3rd party fix from cecilia-sanare until this repo is fixed, as posted in their PR (#50). https://raw.githubusercontent.com/cecilia-sanare/ChatBubbles/cecilia/repo.json
> 
> > 
> 
> > Is this still working as of now?
> 
> 
> 
> I tried the URL today and can't seem to find it in XIVLauncher.

It should still work, but I know there's some finicky-ness with replacing currently installed plugins with one from a third party repo. 

Usually what's worked for me 100% of the time is to remove the plugin, add the third party url, and restart XIV.

**Comment by cecilia-sanare** [comment]
@basedmatt, @EnigmaMoon 
Renamed the plugin to "Chat Bubbles (Unofficial)" so it won't conflict with the 1st party plugin anymore.
Keep in mind I have zero intentions of maintaining that repo longterm and its purely there because I see Chat Bubbles as something I just personally can't live without anymore.

**Comment by Haplo064** [comment]
It's always weird to me to see so much interest in this thing I made.
I'll have it updated (along with some minor fixes) in the next few days.
Mad props to the people doing unnoficial variants for those who can't wait.

**Comment by basedmatt** [comment]
Playing any MMO without chat bubbles has always felt off to me. I think it’s weird they don’t support it natively. But yeah, a lot of people like your work! It’s one of like 4 plugins I have.

**Comment by basedmatt** [comment]
Thanks for this in the meantime by the way, I don’t think anyone expects you to continuously support this repo :D

**Comment by EnigmaMoon** [comment]
Thanks to everyone, especially Cecelia and Haplo! I got the 3rd party fix to work. Coming from WoW to FFXIV, not seeing chat bubbles is foreign to me and I cannot live without them. :D

**Comment by Xbob42** [comment]
> It's always weird to me to see so much interest in this thing I made. I'll have it updated (along with some minor fixes) in the next few days. Mad props to the people doing unnoficial variants for those who can't wait.

Appreciate the updates! And I appreciate the folks doing third-party updates in the meantime. This is one of those "must-have" FFXIV add-ons for a lot of us. The game just feels wrong without it!

**Comment by LadyLightning** [comment]
It's essential for roleplaying in a high-chatscroll environment!

**Comment by adamholdenyall** [comment]
Thanks for the update! Literally the only thing I have Dalamud on for.

**Comment by Ravenette** [comment]
It is legitimately a lifesaver for Roleplay, or honestly just communicating in cluttered areas. I can't really enjoy the game without it by now. So yeah, huge Kudos for updating it and creating it!

**Comment by Toxic-sys** [comment]
how do you get this to work? I cant wait any longer. socializing is big for me and in large crowds its impossible. anyone care to explain?

**Comment by papadeusvult** [comment]
> It's always weird to me to see so much interest in this thing I made. I'll have it updated (along with some minor fixes) in the next few days. Mad props to the people doing unnoficial variants for those who can't wait.

It's hardly surprising, @Haplo064, if you consider that in a sea of contemporary MMORPGs that have chat bubbles built in, FFXIV still doesn't—even after all of its updates over the past nine years now.

It's a saving grace, especially in high traffic and rather social areas in the game.

Personally, I'm hopeful that this outpouring of support and a need for it puts the demand for it into perspective, and helps you to appreciate how much the player-base that uses it likes the work you've done. 

It's probably a side project for you, and I don't doubt you've got other more pressing matters to attend to in your life, but a regularly-updated Chat Bubbles add-on would certainly make for a happier, more content player-base. 

Thank you for your work, and we look forward to new updates moving forward

**Comment by WccKonig** [comment]
> how do you get this to work? I cant wait any longer. socializing is big for me and in large crowds its impossible. anyone care to explain?

Check out cecilia-sanare's temporary fix for ChatBubbles. https://github.com/cecilia-sanare/ChatBubbles

**Comment by ElaraUmbra** [comment]
> 

How much longer do you think till its updated?

**Comment by Ravenette** [comment]
Unless I'm incorrect, another patch just released, so all of Dalamud is currently ded.

**Comment by SleepyBun** [comment]
this plugin really really helps me with my adhd, i have a hard time just looking at the chat box. 
thank you so much for making this, can't wait for the update.

**Comment by MKhayle** [comment]
We are working on this update. There is no ETA for now, but we'll do our best to make it available soon on the main repo.

**Comment by cecilia-sanare** [comment]
The wonderful @MKhayle merged both of my PRs so I ended up opening a PR over on the DalamudPluginsD17 repo to get it deployed!

https://github.com/goatcorp/DalamudPluginsD17/pull/482

**Comment by MKhayle** [comment]
Closing this issue now that ChatBubbles has been updated for Dalamud's API7 and FFXIV's Patch 6.2.

Huge thanks to @cecilia-sanare for helping and making this possible!
