### ISSUE TITLE
options not saving

### ISSUE THREAD

**Issue by decoytrix** [Haplo064/ChatBubbles#53]
When trying to select different color options for things like text or background, the options don't save through a reload.  Relogging or even just disabling and reenabling the plugin will reset the options to their default settings

I seem to remember there being a save button that doesn't exist now, so that might be the issue.

**Comment by MKhayle** [comment]
I can't replicate this issue ; you may have an older config version which hasn't been updated. I'd advise you to follow this process to reset your config file :

- Exit the game if it's running
- Delete/change the file name of your config file in `%appdata%/XIVLauncher/pluginConfigs/ChatBubbles.json`
- Restart the game, and attempt to open config
- if it doesn't show the save option, please type `/xllog`, re-attempt to open the config and report any ChatBubbles-related error which could spawn. 

Thanks !

**Comment by decoytrix** [comment]
Finding the config files helped.  I deleted and reinstalled the plugin.  The save button is there now so I'm confident it will work as before and show the chosen colors on next login.  Thanks.
