### ISSUE TITLE
needs to be updated to work with 6.4

### ISSUE THREAD

**Issue by mallman1** [Haplo064/ChatBubbles#59]
see title

**Comment by Ravenette** [comment]
Yes, please! Such a necessary mod! <3  And thank you, very grateful!

**Comment by Neriek** [comment]
literally all you need to do is open it with visual studio and compile it.. but I realize some people don't want to do that so until Haplo get's around to it here
[chatbubs.zip](https://github.com/Haplo064/ChatBubbles/files/11572010/chatbubs.zip). Use it at your own risk, but I really cbf doing anything malicious to begin with.

**Comment by MKhayle** [comment]
See #58

**Comment by MKhayle** [comment]
(new features are being added along with the upcoming update and I also had to sleep, hence the small delay)

**Comment by MKhayle** [comment]
The update is live.
