### ISSUE TITLE
Text Floods

### ISSUE THREAD

**Issue by Axiarus** [Haplo064/ChatBubbles#61]
Text floods out of the chat bubble.

**Comment by MKhayle** [comment]
![image](https://github.com/Haplo064/ChatBubbles/assets/4359469/c05b5589-95e9-4485-89f4-6b7bd8edc745)
![image](https://github.com/Haplo064/ChatBubbles/assets/4359469/11a1bc97-a77c-4b44-bfaf-503d20a92041)

I can't reproduce your issue. Can you give more context, information as to how it happens, potentially with a screenshot?

**Comment by Haplo064** [comment]
Issue is caused by resizing don't via other plugins.
Not related to this one.
(Can be fixed by restarting your game client regardless)
