### ISSUE TITLE
Bubbles attach to incorrect NPC bones

### ISSUE THREAD

**Issue by Jarey-au** [Haplo064/ChatBubbles#62]
At an inconsistent rate, bubbles will attach to the wrong bones on NPCs. Generally it attaches to their shoulder, but may also attach to hands. As most I can see it is generally the Left shoulder and Right hand.
Typically the issue is solved by turning the plugin off & on again, or waiting for the NPC to speak a second time. Though it will occur inconsistently again when meeting other NPCs.

I've linked an example image, please be advised this contains cropped photos of NPCs in DAWNTRAIL's 6th world zone, in the lvl 99 range of MSQ.
https://i.imgur.com/o3NtCZL.png

**Comment by MKhayle** [comment]
should be fixed
