### ISSUE TITLE
[Issue] Player Chat Bubbles are empty

### ISSUE THREAD

**Issue by illutian** [Haplo064/ChatBubbles#64]
When every I see a player use one of the channels I have selected for bubbles. A bubble appears, but there's no text in the bubble.

Enabled Debug and pulled this every single time I test:
20:03:14.450 | WRN | [ChatBubbles] Unusual AttachmentPoint Detected: 1514557348

Current Bubble "triggers" are: /say, /yell, /shout, and /party. I've color-coded them, and those bubbles are colored correctly, but the text isn't appearing and the bubbles are all the same size. Text color is: 0, 0, 0, 1 (RGBA).

**Comment by MKhayle** [comment]
1/ Have you tried restarting your game
2/ Have you tried resetting your config file and reload the plugin (right click in the Plugin List)?
3/ What is the context? When does that happen?
4/ This should never happen except in specific situations (cutscenes, some story opponents, an enemy-specific attack). Have you been using any plugins which affect the game?

**Comment by illutian** [comment]
Hmm, odd, a reset of the config fixed it.

That is so weird because the only change between my original config and the default that the mod resets to is the bubble colors and the Yalm distance (changed it back to 40 and still works).

Wonder what made it break. 🤔

**Comment by illutian** [comment]
nvm...it's back...maybe it's the PVP???

**Comment by MKhayle** [comment]
Are you maybe using any mods or plugins modifying the bone structure of characters, by any chance?

**Comment by illutian** [comment]
Hmm...might be Artemis Roleplaying Kit. Even though I don't use any animation mod, and use it only for the voice over.

Just disabled it and text once again appeared in the bubbles, re-enabled it and the bubbles are now blank.

Oh and the error is now: 11:11:05.976 | WRN | [ChatBubbles] Unusual AttachmentPoint Detected: -543862499

...guessing the number is a Reference ID of some sort.

Not sure if this helps, but ARK does trigger this: 11:13:22.842 | WRN | "Artemis Roleplaying Kit" is accessing "ObjectTable" outside the main thread. This is deprecated.

Obviously not implying you should fix another mod, but maybe it'll help narrow down why the two aren't playing nice. Given that no animation mod is present.

Oh, and someone else has reported the conflict over on ARK's github.

**Comment by MKhayle** [comment]
I see, so that's not a problem on Chat Bubbles' end. 

I can't and won't provide a fix for this issue as it isn't a normal occurrence (at all).

**Comment by illutian** [comment]
No worries, I'm just glad the cause was found out. I never would have thought body rigs would mess with this so never would have thought to check ARK.
